import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sabbir's Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-color-mode="light" className="light">
      <head>
      <link rel="shortcut icon" href="https://react-icons.github.io/react-icons/favicon.png"/>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
